# Generated by Django 3.2 on 2021-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_y_Apellido', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=50)),
                ('Mensaje', models.CharField(max_length=400)),
            ],
        ),
    ]
